### ISSUE TITLE
References the wrong component

### ISSUE THREAD

**Issue by ghost** [compodoc/compodoc-demo-todomvc-angular#2]
Console output on `ng serve`

```
ERROR in src/app/shared/components/empty-component.ts(3,38): error TS2307: Cannot find module './empty-parent.component'.
```

Update
https://github.com/compodoc/compodoc-demo-todomvc-angular/blob/75ab7a99f93d51924e7a69b4f36ab78a6325d2ac/src/app/shared/components/empty-component.ts#L3

to:
```
import { EmptyParentComponent } from './empty-parent-component';
```

**Comment by vogloblinsky** [comment]
Fixed thanks for the typo
