### ISSUE TITLE
Custom show/Hide sections

### ISSUE THREAD

**Issue by keygjones** [compodoc/compodoc-demo-todomvc-angular#20]
Would be nice to be able to exclude some portions of each page, either with css and selecting sections within each page and use a display:none , so marking sections with id's or classes, or some exclude parameter for the build.

**Comment by vogloblinsky** [comment]
hi @keygjones 
Your issue is for this demo project or compodoc ?

**Comment by keygjones** [comment]
Hi @keygjones ,
I was thinking about compodoc :)

**Comment by vogloblinsky** [comment]
Please move to compodoc repository, thanks ;)
